server:
  port: 8083

spring:
  application:
    name: barriodigital-ms-notify
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin123}
    listener:
      simple:
        retry:
          enabled: true
          max-retries: 3
          initial-interval: 1000ms
          multiplier: 2.0
          max-interval: 5000ms
        default-requeue-rejected: false